// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: proto/cassandra.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CassandraService_SayHello_FullMethodName = "/cassandragrpc.CassandraService/SayHello"
)

// CassandraServiceClient is the client API for CassandraService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CassandraServiceClient interface {
	// Method for sending a "Hello" message between nodes.
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type cassandraServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCassandraServiceClient(cc grpc.ClientConnInterface) CassandraServiceClient {
	return &cassandraServiceClient{cc}
}

func (c *cassandraServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, CassandraService_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CassandraServiceServer is the server API for CassandraService service.
// All implementations must embed UnimplementedCassandraServiceServer
// for forward compatibility.
type CassandraServiceServer interface {
	// Method for sending a "Hello" message between nodes.
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedCassandraServiceServer()
}

// UnimplementedCassandraServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCassandraServiceServer struct{}

func (UnimplementedCassandraServiceServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedCassandraServiceServer) mustEmbedUnimplementedCassandraServiceServer() {}
func (UnimplementedCassandraServiceServer) testEmbeddedByValue()                          {}

// UnsafeCassandraServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CassandraServiceServer will
// result in compilation errors.
type UnsafeCassandraServiceServer interface {
	mustEmbedUnimplementedCassandraServiceServer()
}

func RegisterCassandraServiceServer(s grpc.ServiceRegistrar, srv CassandraServiceServer) {
	// If the following call pancis, it indicates UnimplementedCassandraServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CassandraService_ServiceDesc, srv)
}

func _CassandraService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CassandraServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CassandraService_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CassandraServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CassandraService_ServiceDesc is the grpc.ServiceDesc for CassandraService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CassandraService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cassandragrpc.CassandraService",
	HandlerType: (*CassandraServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _CassandraService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cassandra.proto",
}
