version: '3'
services:
  client:
    build:
      context: ..
      dockerfile: ./docker/DockerfileClient
    container_name: client
    environment:
      NODE_NAME: "Client"
      PEER_ADDRESS: "cassandra-node:50051"
    ports:
      - "50051:50051"
    networks:
      - cassandra-net

  cassandra-node:
    build:
      context: ..
      dockerfile: ./docker/DockerfileNode
    container_name: cassandra-node
    environment:
      NODE_NAME: "Node"
      PEER_ADDRESS: "client:50051"
    ports:
      - "50052:50051"
    networks:
      - cassandra-net

networks:
  cassandra-net:
    driver: bridge